version: 1
reporting: checks-v1
policy:
  pullRequests: public
tasks:
  - $if: 'tasks_for == "github-pull-request"'
    then:
      taskId: {$eval: as_slugid("pr-task")}
      created: {$fromNow: ''}
      deadline: {$fromNow: '1 hour'}
      expires: {$fromNow: '1 day'}
      provisionerId: docker-compose
      workerType: generic-worker
      routes:
        - checks
      metadata:
        name: "PR check"
        description: "Run tests on pull request"
        owner: ${event.pull_request.user.login}@users.noreply.github.com
        source: ${event.repository.html_url}
      payload:
        maxRunTime: 600
        command:
          - - /bin/bash
            - -c
            - >-
              curl -fsSL
              "https://raw.githubusercontent.com/${event.pull_request.head.repo.full_name}/${event.pull_request.head.sha}/run_tests.sh"
              -o /tmp/run_tests.sh &&
              bash /tmp/run_tests.sh
        features:
          taskclusterProxy: true
